# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/dl-from-foundations',
                'doc_host': 'https://AdityaVarmaUddaraju.github.io',
                'git_url': 'https://github.com/AdityaVarmaUddaraju/dl-from-foundations',
                'lib_path': 'dl_from_foundations'},
  'syms': { 'dl_from_foundations.core': {'dl_from_foundations.core.foo': ('core.html#foo', 'dl_from_foundations/core.py')},
            'dl_from_foundations.dlff': { 'dl_from_foundations.dlff.near': ('matmul.html#near', 'dl_from_foundations/dlff.py'),
                                          'dl_from_foundations.dlff.test': ('matmul.html#test', 'dl_from_foundations/dlff.py'),
                                          'dl_from_foundations.dlff.test_eq': ('matmul.html#test_eq', 'dl_from_foundations/dlff.py'),
                                          'dl_from_foundations.dlff.test_near': ('matmul.html#test_near', 'dl_from_foundations/dlff.py')}}}