# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_matmul.ipynb.

# %% auto 0
__all__ = ['test', 'test_eq', 'near', 'test_near']

# %% ../nbs/00_matmul.ipynb 4
import operator
def test(a,b,cmp,cname=None):
    if cname is None: cname = cmp.__name__
    assert cmp(a,b),f"{cname}:\n{a}\n{b}"

def test_eq(a,b): return test(a,b,operator.eq,'==')

# %% ../nbs/00_matmul.ipynb 22
def near(a,b): return torch.allclose(a, b, rtol=1e-3, atol=1e-5)
def test_near(a,b): test(a,b,near)
